# Config file for automatic testing at travis-ci.org

language: python
arch:
  - arm64
  - amd64
python:
  - 3.8

install: pip install pytest

# command to run tests, e.g. python setup.py test
script: py.test
sudo: false
